

//function to be call when the boat rolling angle is greater than 45°
void angle_exceeded();

//initialization of the boat rolling monitoring 
void init_rolling_monitoring();

//launch the boat rolling monitoring 
void launch_rolling_monitoring();

//check the boat rolling angle
void rolling_angle_checking();

//Global variable :  
	// 0 -> angle OK 
	// 1 -> angle KO 
int mode ; 